### ISSUE TITLE
MIDI mode is activated only at the attack of the note

### ISSUE THREAD

**Issue by rugubara** [x42/fat1.lv2#10]
I've compiled your fat1 plugin and trying to use it on a couple of tracks in ardour 5.12

I have a stereo track with a vocal signing off tune and I would like to correct it. The vocal has no vibrato. The fully automatic mode hesitates between two adjacent notes. I've made a midi track with correct notes and sidechained the midi output of the track. 

The autotune plugin is set to MIDI mode. I can see that the right note is activated but for an instant only at the attack of the midi note. I have a midi organ on the track so I can hear that the note stays on as expected.

What could be the reason?

**Comment by x42** [comment]
Did you compile recent git (v0.6.0) ? 

An older version of the plugin had this issue if you clicked "MIDI panic" in the GUI at least once.

**Comment by x42** [comment]
Right-click on the MIDI-keyboard v0.6.0 will show the version bottom, middle (earlier versions don't)

![Screenshot at 2019-10-17 21-23-06](https://user-images.githubusercontent.com/30246/67040754-69f08d80-f124-11e9-8186-8a0ada00d095.png)

**Comment by rugubara** [comment]
Since I'm running Gentoo and made the ebuild myself, I'm sure I run 0.5.3. Making 0.6.0 is some 15 min. Will get back soon.

**Comment by rugubara** [comment]
Running 0.6.0 now. The problem went away. Although, the screenshot doesn't match:
![Screenshot from 2019-10-17 22-37-55](https://user-images.githubusercontent.com/9335047/67041726-ee480e00-f12e-11e9-8b8e-35fa642da521.png)

**Comment by x42** [comment]
Looks like you have a HiDPI display, tou can right-click on a blank-space and scale, the GUI,
otherwise it looks fine.

**Comment by x42** [comment]
Closing, since the original issue has been resolved.
