### ISSUE TITLE
Cycle calculation under noisy conditions

### ISSUE THREAD

**Issue by x42** [x42/fat1.lv2#15]
A follow up of #13 

> ```
> crash ahead: x=9.988863e-01 y=9.988863e-01 z=9.988863e-01 _cycle=-nan
> crash ahead: x=9.999988e-01 y=9.999988e-01 z=9.999987e-01 _cycle=inf
> ```
> I had to blow on my microphone for some time but you never know when it happens in live ! Maybe it's better to switch x, y and z to doubles after all, no ?

Suggestion: replace

https://github.com/x42/fat1.lv2/blob/5a44436e7d073a4598a9a1240b41c7f297897b4c/src/retuner.cc#L442-L449

with
```
if  ((z - 2 * y + x) >  2e-9f) {
  _cycle = j + 0.5f * (x - z) / (z - 2 * y + x - 1e-9f);
}
```
(the 1e-9 here is to prevent denormals)

**Comment by jean-emmanuel** [comment]
This seem to bypass normal cycle detection as well. What about this ?
```c++
 if (isnan(_cycle) || isinf(_cycle))
    _cycle = 0;
```

**Comment by jean-emmanuel** [comment]
a551bd2 works fine !

**Comment by x42** [comment]
Thanks for checking!
