### ISSUE TITLE
Add microtuning support

### ISSUE THREAD

**Issue by tank-trax** [x42/fat1.lv2#25]
This is a feature request to add microtuning support either with SCL/KBM support, MTS-ESP or both

https://github.com/ODDSound/MTS-ESP
https://github.com/surge-synthesizer/tuning-library

Thanks for your consideration

**Comment by x42** [comment]
The plugin internally relies on an octave independent 12 tone system. So adding support for scala is not really an option, only a very limited subset of scl files would be applicable.

**Comment by tank-trax** [comment]
I appreciate the explanation.

I hadn't taken a closer look at this plugin prior to my request and wasn't aware that it had microtonal capabilities (albeit restricted to 12 notes per octave). That in it itself does present some interesting possibilities. I also noticed that pitch bend is enabled which makes for a potential fit with Xen Midi Retuner (will test it to see if it works or not).

Thanks
