### ISSUE TITLE
Does not work in Ardour 8

### ISSUE THREAD

**Issue by ahstro** [x42/fat1.lv2#29]
Hi 😊

Trying to use this plugin in Ardour, but it's just throwing this non-descript error without further explanation, and the logs mentioned are empty. I've tried both with the version in the Arch Linux repos and downloading latest version from [x42-plugins.com](https://x42-plugins.com/x42/x42-autotune). Seems to be happening with all x42 plugins I try. Any ideas where I can dig to find any logs or error messages?

Thanks!

![bork](https://github.com/x42/fat1.lv2/assets/3090888/978cf775-1909-4e7a-af0f-f3c1d4d82821)

**Comment by x42** [comment]
Are you perhaps using the wrong architecture?  32 bit intel on a 64bit system or vice versa?
When you start Ardour from the commandline, is there anything on stdout/stderr?

**Comment by ahstro** [comment]
Well, guess I was just making silly mistakes... Guessing rescanning plugins wasn't enough to find the manually added last version; restarting Ardour did the trick 🤦‍♀️ Guess I'll go try to get the Arch Linux repo version updated instead. Thanks for the quick reply and the plugin suite! 🙏
