### ISSUE TITLE
Plugin not showing up in Ableton

### ISSUE THREAD

**Issue by mijorus** [x42/fat1.lv2#30]
Hi, I installed the x42-autotune plugin using the .pkg available from your website for my architecture, but it is not showing up in any DAW.

**Comment by x42** [comment]
Well, try Reaper, or Harrison Mixbus, or Tracktion,... For the plugin to show up the DAW needs to support LV2 plugins.

**Comment by mijorus** [comment]
> Well, try Reaper, or Harrison Mixbus, or Tracktion,... For the plugin to show up the DAW needs to support LV2 plugins.

Yeah, sorry for that. Ableton does not support lv2 plugins. I ended up using Reaper with Blackhole to record my microphone, for anyone who's interested
